name:
    Zip and deploy to webstore
on:
    push:
        branches:
            - 'master'
jobs:
    zip_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                node-version: 14
            - name: Building project
              run: npm run build
            - name: 🚨 Zipping
              run: cd build && zip -r build.zip *
            - uses: trmcnvn/chrome-addon@v2
              name: ✅ Deploying to webstore
              with:
                  extension: bbaegmboolkgheghdaoahaabjnkofmdm
                  zip: build/build.zip
                  client-id: ${{ secrets.CLIENT_ID }}
                  client-secret: ${{ secrets.CLIENT_SECRET }}
                  refresh-token: ${{ secrets.REFRESH_TOKEN }}
